apiVersion: v1
kind: Service
metadata:
  name: projectpulse-api
  namespace: projectpulse
spec:
  type: ClusterIP
  selector:
    app: projectpulse-api
  ports:
    - name: http
      port: 4000
      targetPort: http
